max_width = 80
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
indent_style = "Block"
use_small_heuristics = "Default"
fn_call_width = 40
attr_fn_like_width = 40
struct_lit_width = 0
struct_variant_width = 0
array_width = 20
chain_width = 30
single_line_if_else_max_width = 0
wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 70
comment_width = 60
normalize_comments = true
normalize_doc_attributes = true
format_strings = true
format_macro_matchers = false
format_macro_bodies = true
skip_macro_invocations = []
hex_literal_case = "Preserve"
empty_item_single_line = false
struct_lit_single_line = false
fn_single_line = false
where_single_line = true
imports_indent = "Block"
imports_layout = "Vertical"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
type_punctuation_density = "Wide"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Front"
remove_nested_parens = true
combine_control_expr = false
short_array_element_width_threshold = 10
overflow_delimited_expr = false
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
match_arm_blocks = true
match_arm_leading_pipes = "Always"
force_multiline_blocks = true
fn_params_layout = "Vertical"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
trailing_semicolon = false
trailing_comma = "Vertical"
match_block_trailing_comma = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
edition = "2021"
version = "Two"
inline_attribute_width = 0
format_generated_files = true
merge_derives = true
use_try_shorthand = false
use_field_init_shorthand = false
force_explicit_abi = true
condense_wildcard_suffixes = true
color = "Auto"
required_version = "1.5.2"
unstable_features = false
disable_all_formatting = false
skip_children = false
hide_parse_errors = false
error_on_line_overflow = false
error_on_unformatted = false
ignore = []
emit_mode = "Files"
make_backup = false
